Refs #153 Upgrade jQuery to 1.12.4
HybirdCorp/creme_crm pull request #161
Opened 2021-02-26 08:12 UTC by joehybird

Upgrade to last compatible jQuery version with our codebase and do some cleanup work to prepare migration to 2.x

TODO : Changelog

2021-02-26 10:17 UTC, genglert requested changes

2021-02-26 10:59 UTC, joehybird commented on creme/creme_core/static/creme_core/js/lib/browser.js
> +    Copyright (C) 2021  Hybird
Ah! My pre-push checks aren't working perfectly -_-'

2021-02-26 15:06 UTC, genglert requested changes

2021-02-26 15:06 UTC, genglert commented on CHANGELOG.txt
> +    # The version of jQuery has been upgraded to "1.12.4"
You can remove this one (django is in users' section because of installation/virtual env)

2021-02-26 15:06 UTC, genglert commented on CHANGELOG.txt
> +                * Some creme.ajax.* functions are now deprecated; Use creme.ajax.Query instead:
s/Use/use

2021-02-26 15:06 UTC, genglert commented on CHANGELOG.txt
> +                * All 'creme.layout.Layout' classes are deprecated; Use CSS instead
s/Use/use

2021-03-01 08:50 UTC, genglert approved these changes

2021-03-01 09:25 UTC, merged