Reduce calls to populate within test suites; Use a small database of towns for CI
HybirdCorp/creme_crm pull request #412
Opened 2022-07-22 08:46 UTC by joehybird

2022-08-17 08:23 UTC, genglert requested changes
Add a comment in settings.py about the existence of "geolocation/data/test.towns.france.csv.zip" which can be useful for unit tests

2022-08-23 16:43 UTC, genglert requested changes
Why the option "'--no-populate'" made its come back ?

2022-08-23 16:43 UTC, genglert commented on creme/settings.py
> +    # For the CI a lighter version of the file exists with only the "chef-lieu"
s/CI/unit tests

2022-08-23 17:11 UTC, joehybird commented
???

2022-08-24 07:01 UTC, joehybird commented on creme/settings.py
> +    # For the CI a lighter version of the file exists with only the "chef-lieu"
> Why the option "'--no-populate'" made its come back ?

Merge issue on my local branch -_-

2022-08-24 07:15 UTC, genglert requested changes
Can you fix up/squash your commits please (I think 2 commits -- geolocation & test-populate --- are sufficient) ?

2022-08-24 15:10 UTC, genglert approved these changes

2022-08-24 15:29 UTC, merged