New EnumerableChoiceField for autocompletion + pagination
HybirdCorp/creme_crm pull request #460
Opened 2022-10-12 10:35 UTC by joehybird

2022-10-12 13:13 UTC, genglert requested changes

2022-10-12 13:13 UTC, genglert commented on creme/creme_core/tests/forms/test_enumerable.py
> +        farming, industry, software = FakeSector.objects.order_by('pk').all()
`.all()` is useless

2022-10-12 13:13 UTC, genglert commented on creme/creme_core/tests/forms/test_enumerable.py
> +        self.assertEqual([], enumerable.to_python([99999]))
`_CremeTestCase.UNUSED_PK` ??

2022-10-12 13:13 UTC, genglert commented on creme/creme_core/tests/forms/test_enumerable.py
> +        self.assertEqual(None, field.empty_label)
assertIsNone

2022-10-12 14:38 UTC, joehybird commented on CHANGELOG.txt
> +    # Creme user selection fields now use paginated autocompletion.
yes for now only users

2022-10-12 14:39 UTC, joehybird commented on creme/creme_core/models/fields.py
> +                empty_label=_('Select a user...'),
Oh I forgot this one

2022-10-13 04:45 UTC, joehybird commented on creme/creme_core/tests/forms/test_enumerable.py
> +        self.assertEqual([], enumerable.to_python([99999]))
Thx I wasn't able to retrieve it 😓

2022-10-13 11:07 UTC, genglert requested changes

2022-10-14 07:39 UTC, genglert approved these changes

2022-10-14 08:07 UTC, merged