Add support for creation in Select2 widgets
HybirdCorp/creme_crm pull request #468
Opened 2022-10-24 13:46 UTC by joehybird

2022-10-24 17:04 UTC, genglert requested changes

2022-10-27 18:01 UTC, genglert requested changes

2022-11-04 12:56 UTC, joehybird commented on creme/activities/forms/fields.py
> +class ActivitySubTypeField(CreatorEnumerableChoiceField):
Still used in mass import for the moment, so I cannot deprecate it

2022-11-07 10:03 UTC, genglert requested changes

2022-11-07 14:08 UTC, genglert approved these changes

2022-11-07 14:09 UTC, merged