Fix an issue in listview date search when typing and selecting a date at the same time.
HybirdCorp/creme_crm pull request #487
Opened 2022-11-23 10:14 UTC by joehybird

2022-11-23 11:08 UTC, genglert approved these changes

2022-11-26 12:33 UTC, joehybird commented
Found an issue in multiple invalid search fields handling -> back to WIP

2022-12-01 13:51 UTC, genglert requested changes

2022-12-01 13:51 UTC, genglert commented on creme/creme_core/static/creme_core/js/list_view.core.js
> +            console.log('submitState', data);
Trash

2022-12-01 13:51 UTC, genglert commented on creme/creme_core/static/creme_core/js/list_view.core.js
> +                return console.log('   ', $(this).attr('name'), $(this).val(), !$(this).is('.invalid'));
??

2022-12-05 16:22 UTC, genglert approved these changes

2022-12-05 16:31 UTC, merged