Fix history infinite loop on url hash change
HybirdCorp/creme_crm pull request #611
Opened 2023-07-28 05:22 UTC by joehybird

2023-09-12 08:07 UTC, genglert requested changes

2023-09-12 08:07 UTC, genglert commented on creme/activities/views/calendar.py
> +    return timestamp
"timestamp" variable is 'useless'.

2023-09-12 08:07 UTC, genglert commented on creme/activities/views/calendar.py
> +def toRFC3339(value):
I presume you can add some static typing here because we love that kind of things.

2023-09-12 08:07 UTC, genglert commented on creme/activities/views/calendar.py
> +            end = end + timedelta(minutes=1)
+=

2023-09-12 08:07 UTC, genglert commented on creme/settings.py
> +    # ('creme.activities',       'activities/css/fc3-creme.css'),
Can you add a comment like "to be deleted in creme 2.7' please (in order in do not forget to remove the related files) ?

2023-09-14 12:59 UTC, joehybird commented on creme/activities/views/calendar.py
> +    return timestamp
yes, this time the print was removed 😄

2023-09-15 13:28 UTC, genglert requested changes

2023-09-15 13:28 UTC, genglert commented on creme/activities/views/calendar.py
> -def _js_timestamp_to_datetime(timestamp):
Not in changelog.

2023-09-15 13:28 UTC, genglert commented on creme/activities/views/calendar.py
> +# from creme.creme_core.utils.dates import make_aware_dt
Moved here by your IDE I presume.

2023-09-15 13:28 UTC, genglert commented on creme/activities/views/calendar.py
> +def fromRFC3339(timestamp: str):
Why not type for the retuned value?

2023-09-15 13:28 UTC, genglert commented on creme/activities/views/calendar.py
> +def toRFC3339(value: datetime):
Idem

2023-09-15 13:28 UTC, genglert commented on creme/settings.py
> +    # ('creme.activities', 'activities/js/lib/fullcalendar-3.10.2.js'),
`# To be deleted in in creme 2.7`

2023-09-15 13:28 UTC, genglert commented on creme/settings.py
> +    # ('creme.activities',    'activities/js/activities-calendar-v3.js'),
`# To be deleted in in creme 2.7`

2023-09-15 15:27 UTC, genglert approved these changes

2023-09-18 07:18 UTC, merged