Improve d3 charts and tools : fix axis formatting issues & allow scrolling of charts with too many values.
HybirdCorp/creme_crm pull request #617
Opened 2023-08-29 14:09 UTC by joehybird

2023-09-01 09:45 UTC, genglert requested changes

2023-09-01 09:45 UTC, genglert commented on CHANGELOG.txt
> +                    - creme.d3ColorRange now accept a function. Useful for computed ranges.
You put this part in the "deprecations" section. Add a "Apps" section at the end of "non breaking changes" & move this part to it.

2023-09-01 09:45 UTC, genglert commented on CHANGELOG.txt
> +                        - Bar text is visible only on mouse hover if it is too small.
A small explanation of the improvements in the "users side" part would be better.
scrollog => scrolling I suppose.

2023-09-01 09:45 UTC, genglert commented on creme/reports/static/icecream/reports/css/reports.css
> +}
Not in "Chantilly" theme?

2023-09-02 03:24 UTC, joehybird commented on creme/reports/static/icecream/reports/css/reports.css
> +}
good catch :)

2023-09-02 08:11 UTC, genglert commented
Please edit the PR to target the branch 'v2.5-rc6'.

2023-09-04 07:56 UTC, merged