Add configuration for calendar view per role.
HybirdCorp/creme_crm pull request #639
Opened 2023-10-04 09:27 UTC by joehybird

2023-10-05 14:20 UTC, genglert requested changes

2023-10-05 14:20 UTC, genglert commented on creme/activities/models/config.py
> +        )[0]
Useless, it's wrapper with not intelligence. Even in unit tests once you'll just rely on the default configuration create in populate.py I'm not sure it we'll be useful (and if it's useful, create a test case method).

2023-10-05 14:20 UTC, genglert commented on creme/activities/models/config.py
> +        return self.create_if_needed(role=None, superuser=False)
Useless ; just inline the call in populate.py

2023-10-05 14:20 UTC, genglert commented on creme/activities/models/config.py
> +            config = CalendarConfigItem()
409 error (check that logger is still useful after that).

2023-10-05 14:26 UTC, joehybird commented on creme/activities/tests/test_calendar.py
> +        with override_tz(timezone_name):
nope, the "current timezone" and the a middleware is doing the same thing as `override_tz(user.time_zone)`

2023-10-05 14:29 UTC, joehybird commented on creme/activities/tests/test_config.py
> +
Why not but `test_config_create__role_choices` already testing this case.

2023-10-05 14:32 UTC, joehybird commented on creme/activities/urls.py
> +        r'^calendar/settings/edit/(?P<role>\w+)[/]?$',
I'm using `RoleRelatedMixin` to handle `default`, `superuser` & `role.pk` values.

2023-10-05 16:06 UTC, genglert commented on creme/activities/urls.py
> +        r'^calendar/settings/edit/(?P<role>\w+)[/]?$',
It's still non relevant. there are 2 cases :
- Bricks/Menu configuration where the configurations are exploded into many small items (1 item -- line in data base == 1 brick/menu-entry). So you have to retrieve all these small items related ton the given role to get the whole configuration.
- Custom-forms/Calendars where 1 item store the whole configuration related to a role ; the simplest way is to retrieve them by their ID.

2023-10-18 10:30 UTC, genglert requested changes

2023-10-18 10:30 UTC, genglert commented on creme/activities/tests/test_config.py
> +        super().setUp()
Useless now

2023-10-18 10:30 UTC, genglert commented on creme/activities/tests/test_config.py
> +        self.assertEqual(week_default.as_dict(), default.as_dict())
assertDictEqual

2023-10-18 10:30 UTC, genglert commented on creme/activities/tests/test_config.py
> +        super_user = self.create_user(username='super', is_superuser=True)
You could use get_root_user() to avoid a write in DB).

2023-10-18 10:30 UTC, genglert commented on creme/activities/tests/test_config.py
> +        self.assertTrue(CalendarConfigItem.objects.filter(pk=config.pk).exists())
self.assertStillExists(config)

2023-10-18 10:30 UTC, genglert commented on creme/activities/tests/test_config.py
> +        self.assertFalse(CalendarConfigItem.objects.filter(pk=config.pk).exists())
self.assertDoesNotExist(config)

2023-10-18 10:30 UTC, genglert commented on creme/activities/urls.py
> +        r'^calendar/settings/edit/(?P<object_id>\d+)[/]?$',
'item_id' (+ `pk_url_kwarg = 'item_id'` in view I assume).

2023-10-18 10:30 UTC, genglert commented on creme/activities/views/calendar.py
> +        config = CalendarConfigItem.objects.for_user(user)
Inline it

2023-10-18 10:30 UTC, genglert commented on creme/activities/views/calendar.py
> +    # model = BrickHomeLocation
crap

2023-10-18 13:44 UTC, joehybird commented on creme/activities/locale/fr/LC_MESSAGES/django.po
> -msgctxt "activities-meeting"
Yes I got a conflict on this file

2023-10-18 18:22 UTC, genglert approved these changes

2023-10-19 15:14 UTC, merged