New D3LineChart that draws a curved line
HybirdCorp/creme_crm pull request #652
Opened 2023-10-26 11:36 UTC by joehybird

2023-10-27 09:59 UTC, genglert requested changes
What if the user use JQplot? I presume it won't work => should we officially remove JQplot?

2023-10-27 09:59 UTC, genglert commented on CHANGELOG.txt
> +                - Add 'linechart' to the available charts.
It's a user-sided feature.

2023-10-27 09:59 UTC, genglert commented on creme/reports/locale/fr/LC_MESSAGES/django.po
Update the date in the header too.

2023-10-27 09:59 UTC, genglert commented on creme/sketch/bricks.py
> +        return props
Useless variable.

2023-10-30 09:24 UTC, joehybird commented
> What if the user use JQplot? I presume it won't work => should we officially remove JQplot?

Yes it won't work. And yes we should officially remove jqplot, the only missing feature (for me) was the tooltip and it is done in this PR event if not used in the other charts, but it is easy to add now.

2023-11-07 09:24 UTC, genglert approved these changes

2023-11-07 09:30 UTC, merged