POC buttons config v2
HybirdCorp/creme_crm pull request #81
Opened 2020-08-07 14:26 UTC by hsmett

2020-09-18 08:51 UTC, genglert commented on creme/settings.py
> -JAVASCRIPT_DEBUG = DEBUG
I'd prefer a separated patch with an entry in the Changelog ("unused setting XXX was removed ..."

2020-09-18 08:54 UTC, genglert commented on creme/creme_config/templatetags/creme_config_tags.py
> +def render_buttons_placeholders(buttons, empty_label):
Prefix by 'config_'

2020-09-18 13:03 UTC, genglert commented on creme/creme_config/forms/widgets.py
> +
1. I try to remove the old "MyEntityEditForm" classes to replace them by "MyEntityEditionForm". So for consistency 'ButtonMenuEditionWidget' would be better.
2. Hum in 'creme_core/forms/widgets' we found XXCreatorWidget, XXXSelector, XXXEditionWidget. That's not very consistent, but the last pattern matches my remark in 1. And so ButtonMenuEditor & ButtonMenuEditorWidget could be used to. Choose one.
3. Don't forget to rename the template too ; even if you keep the 'Widget' suffix in the class, remove it from the file-name (like TimeWidget => 'widgets/time.html')

2020-09-18 13:09 UTC, genglert commented on creme/creme_config/forms/widgets.py
> +        self.choices = list(choices)
self.choices = [*choices]

2020-09-18 13:30 UTC, genglert commented on creme/creme_config/templates/creme_config/bricks/button-menu.html
> +{% load creme_config_tags %}
At the beginning of the file, with other loads.

2020-09-18 13:43 UTC, genglert commented on creme/creme_config/bricks.py
> +        get_ct = ContentType.objects.get_for_id
The field 'ButtonMenuItem.content_type' is a CTypeForeignKey, which automatically use ContentType.objects.get_for_id(). So this optimzation is useless.

2020-11-02 10:51 UTC, genglert requested changes

2020-11-06 08:53 UTC, hsmett commented on creme/creme_config/forms/button_menu.py
> +
I am surprised too, I don't know how it happened. I'm moving it.

2020-11-06 14:59 UTC, genglert requested changes

2020-11-06 14:59 UTC, genglert commented on creme/creme_config/tests/test_widgets.py
> +class ButtonMenuEditWidgetTestCase(CremeTestCase):
ButtonMenuEdit-ION-WidgetTestCase to be consistent

2020-12-18 13:07 UTC, genglert requested changes

2020-12-18 13:07 UTC, genglert commented on creme/creme_config/locale/fr/LC_MESSAGES/django.po
> +"disponible et celle des boutons sélectionnés pour activer ou désactiver "
disponibleS

2020-12-18 13:31 UTC, joehybird requested changes

2020-12-18 13:31 UTC, joehybird commented on creme/creme_config/static/creme_config/js/widgets.js
> +        );
There is a String.prototype.template method in creme similar to an extremely simplified es6 one.
```suggestion
return $((
    '<span class="menu_button" title="${description}">' +
        '${label}<input type="hidden" name="${name} val="${value}"/>' +
    '</span>'
).template(choice)).prop("disabled", !choice.selected);
```

2020-12-18 13:31 UTC, joehybird commented on creme/creme_config/static/creme_config/js/widgets.js
> +        choices.map(
`.each(` will do the job no ? :smile:

2020-12-18 13:31 UTC, joehybird commented on creme/creme_config/templates/creme_config/forms/widgets/buttonmenu-editor.html
> +<script type="text/javascript">
Hum... you can create a creme widget instead off initialize it in scripts. But if is the widget is used once, why not.

2020-12-18 13:31 UTC, joehybird commented on creme/creme_config/templates/creme_config/forms/widgets/buttonmenu-editor.html
> +            widgetAttrsId: '{{widget.attrs.id}}'
Please pass directly the jquery element to the "constructor"
```
creme.initButtonMenuWidget($('#{{widget.attrs.id}}'), { ... })
```

2020-12-18 13:31 UTC, joehybird commented on creme/creme_config/static/creme_config/js/widgets.js
> +        new Sortable(  // eslint-disable-line
I guess that the 'new not returned' error was annoying you :smile:

2020-12-18 13:31 UTC, joehybird commented on creme/creme_config/static/creme_config/js/widgets.js
> +            onSort: function eventHandler(event) {
A bit repetitive, can you factorize this function ?

2020-12-18 15:06 UTC, genglert approved these changes

2020-12-18 15:12 UTC, joehybird approved these changes

2020-12-18 15:48 UTC, merged